name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
      - "releases/v*"
  pull_request:
    branches:
      - "releases/v*"
      - development

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
