name: Test Suites

# We are a reusable Workflow only
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: false

  # Manual Trigger
  workflow_dispatch:

env:
  MODULE_ID: ${{ github.event.repository.name }}
  JDK_VERSION: 21

jobs:
  tests:
    name: Tests ${{ github.event.repository.name }}
    runs-on: ${{ matrix.os }}
    env:
      DB_USER: root
      DB_PASSWORD: root
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest" ]
        experimental: [ false ]
        #include:
          #- jdkVersion: "17"
          #  os: "windows-latest"
          #  experimental: true
          # Disabled for now until we can figure out the gradle matrix
          #- jdkVersion: "17"
          #  os: "ubuntu-latest"
          #  experimental: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup BoxLang
        uses: ortus-boxlang/setup-boxlang@1.0.0

      - name: Test Module
        run: |
          mkdir -p ~/.boxlang/modules
          ln -s "$(pwd)" ~/.boxlang/modules/"$(basename "$(pwd)")"
          boxlang --version

      # UNCOMMENT THE FOLLOWING LINES TO ENABLE SLACK NOTIFICATIONS
      # - name: Inform Slack
      #   if: ${{ failure() && github.ref == 'refs/heads/development' }}
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_CHANNEL: coding
      #     SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
      #     SLACK_ICON_EMOJI: ":bell:"
      #     SLACK_MESSAGE: "${{ env.MODULE_ID }} Tests FAILED!  You broke the build! :("
      #     SLACK_TITLE: "${{ env.MODULE_ID }} Build Failure"
      #     SLACK_USERNAME: CI
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}